import CAMERON_ACTIVE_CASES from './CAMERON_ACTIVE_CASES';
import CAMERON_DEFAULT_CASES from './CAMERON_DEFAULT_CASES';
import CAMERON_DEFAULT_DEATHS from './CAMERON_DEFAULT_DEATHS';
import CAMERON_DEFAULT_RECOVERIES from './CAMERON_DEFAULT_RECOVERIES';

import HIDALGO_ACTIVE_CASES from './HIDALGO_ACTIVE_CASES';
import HIDALGO_DEFAULT_CASES from './HIDALGO_DEFAULT_CASES';
import HIDALGO_DEFAULT_DEATHS from './HIDALGO_DEFAULT_DEATHS';
import HIDALGO_DEFAULT_RECOVERIES from './HIDALGO_DEFAULT_RECOVERIES';

import STARR_ACTIVE_CASES from './STARR_ACTIVE_CASES';
import STARR_DEFAULT_CASES from './STARR_DEFAULT_CASES';
import STARR_DEFAULT_DEATHS from './STARR_DEFAULT_DEATHS';
import STARR_DEFAULT_RECOVERIES from './STARR_DEFAULT_RECOVERIES';

import WILLACY_ACTIVE_CASES from './WILLACY_ACTIVE_CASES';
import WILLACY_DEFAULT_CASES from './WILLACY_DEFAULT_CASES';
import WILLACY_DEFAULT_DEATHS from './WILLACY_DEFAULT_DEATHS';
import WILLACY_DEFAULT_RECOVERIES from './WILLACY_DEFAULT_RECOVERIES';

import PRESS_RELEASES from './PRESS_RELEASES';

import RESOURCES from './RESOURCES';

const CORE_ENDPOINT_ARRAY = [
  "cases",
  "deaths",
  "recoveries"
]

const ENDPOINT_MAP = {
  "cases": "Cases",
  "deaths": "Deaths",
  "recoveries": "Recoveries",
  "active": "Active Cases",
  "home": "home",
}

const ENDPOINT_SINGULAR_MAP = {
    "cases": "case",
    "deaths": "death",
    "recoveries": "recovery",
}

const CATEGORY_MAP = {
  "Cities": "City",
  "Ages": "Age Range",
  "Transmission": "Transmission",
  "Gender": "Gender",
}

const LINE_COLOR_MAP = {
  "active": "#2B8AC5",
  "recoveries": "#2E8B57",
  "deaths": "#000",
  "cases": "#2B8AC5",
  "hidalgo": "#2B8AC5",
  "cameron": "#2E8B57",
  "starr": "#DDA0DD",
  "willacy": "#FFFF99"
}

const GRAPH_COLOR_MAP = {
  "active": "grey",
  "recoveries": "#ebffeb",
  "deaths": "black",
  "cases": "#700D00",
  "home": "grey"
}

export {
  PRESS_RELEASES,
  RESOURCES,
  ENDPOINT_MAP,
  ENDPOINT_SINGULAR_MAP,
  CATEGORY_MAP,
  CORE_ENDPOINT_ARRAY,
  CAMERON_ACTIVE_CASES,
  CAMERON_DEFAULT_CASES,
  CAMERON_DEFAULT_DEATHS,
  CAMERON_DEFAULT_RECOVERIES,
  HIDALGO_ACTIVE_CASES,
  HIDALGO_DEFAULT_CASES,
  HIDALGO_DEFAULT_DEATHS,
  HIDALGO_DEFAULT_RECOVERIES,
  STARR_ACTIVE_CASES,
  STARR_DEFAULT_CASES,
  STARR_DEFAULT_DEATHS,
  STARR_DEFAULT_RECOVERIES,
  WILLACY_ACTIVE_CASES,
  WILLACY_DEFAULT_CASES,
  WILLACY_DEFAULT_DEATHS,
  WILLACY_DEFAULT_RECOVERIES,
  LINE_COLOR_MAP,
  GRAPH_COLOR_MAP,
};
