const DEFAULT_CORONA_DATA = [
  {
    "Date": "3/18",
    "Count": 0,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/19",
    "Count": 1,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/20",
    "Count": 2,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/21",
    "Count": 6,
    "Cases": 4,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 1,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/22",
    "Count": 6,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 2,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/23",
    "Count": 6,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 2,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/24",
    "Count": 7,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 5,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/25",
    "Count": 10,
    "Cases": 3,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 8,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/26",
    "Count": 13,
    "Cases": 3,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 11,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 3,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/27",
    "Count": 13,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 18,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/28",
    "Count": 20,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 27,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/29",
    "Count": 20,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 28,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/30",
    "Count": 26,
    "Cases": 6,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 38,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 2,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/31",
    "Count": 26,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 46,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/01",
    "Count": 37,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 62,
    "CasesHidalgo": 16,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/02",
    "Count": 55,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 79,
    "CasesHidalgo": 17,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/03",
    "Count": 52,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 10,
    "CountHidalgo": 86,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/04",
    "Count": 66,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 1,
    "CountHidalgo": 86,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 6,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 1,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/05",
    "Count": 76,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 99,
    "CasesHidalgo": 13,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/06",
    "Count": 89,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 0,
    "CountHidalgo": 113,
    "CasesHidalgo": 14,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/07",
    "Count": 89,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 7,
    "CountHidalgo": 127,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/08",
    "Count": 94,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 5,
    "CountHidalgo": 130,
    "CasesHidalgo": 11,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 8,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 4,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/09",
    "Count": 99,
    "Cases": 29,
    "Deaths": 2,
    "Recoveries": 22,
    "CountHidalgo": 136,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/10",
    "Count": 111,
    "Cases": 12,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 161,
    "CasesHidalgo": 35,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 10,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/11",
    "Count": 130,
    "Cases": 36,
    "Deaths": 0,
    "Recoveries": 17,
    "CountHidalgo": 168,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/12",
    "Count": 130,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 170,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/13",
    "Count": 143,
    "Cases": 21,
    "Deaths": 0,
    "Recoveries": 8,
    "CountHidalgo": 167,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/14",
    "Count": 163,
    "Cases": 23,
    "Deaths": 0,
    "Recoveries": 3,
    "CountHidalgo": 179,
    "CasesHidalgo": 19,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/15",
    "Count": 167,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 11,
    "CountHidalgo": 184,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 2,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 6,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/16",
    "Count": 170,
    "Cases": 16,
    "Deaths": 1,
    "Recoveries": 12,
    "CountHidalgo": 190,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 3,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 2,
    "CountWillacy": 6,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/17",
    "Count": 172,
    "Cases": 9,
    "Deaths": 1,
    "Recoveries": 6,
    "CountHidalgo": 194,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 3
  },
  {
    "Date": "4/18",
    "Count": 184,
    "Cases": 19,
    "Deaths": 1,
    "Recoveries": 6,
    "CountHidalgo": 207,
    "CasesHidalgo": 13,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/19",
    "Count": 184,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 213,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/20",
    "Count": 187,
    "Cases": 12,
    "Deaths": 1,
    "Recoveries": 8,
    "CountHidalgo": 206,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 14,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 1
  },
  {
    "Date": "4/21",
    "Count": 185,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 11,
    "CountHidalgo": 193,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 20,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/22",
    "Count": 173,
    "Cases": 12,
    "Deaths": 3,
    "Recoveries": 21,
    "CountHidalgo": 181,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 17,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/23",
    "Count": 177,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 5,
    "CountHidalgo": 167,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 23,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/24",
    "Count": 181,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 6,
    "CountHidalgo": 160,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 16,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/25",
    "Count": 193,
    "Cases": 12,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 164,
    "CasesHidalgo": 4,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 3,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/26",
    "Count": 193,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 169,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/27",
    "Count": 199,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 4,
    "CountHidalgo": 150,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 20,
    "CountStarr": 2,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/28",
    "Count": 200,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 8,
    "CountHidalgo": 147,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 7,
    "CountStarr": 2,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/29",
    "Count": 206,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 7,
    "CountHidalgo": 136,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 20,
    "CountStarr": 3,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/30",
    "Count": 207,
    "Cases": 11,
    "Deaths": 1,
    "Recoveries": 9,
    "CountHidalgo": 133,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 13,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/01",
    "Count": 212,
    "Cases": 9,
    "Deaths": 0,
    "Recoveries": 4,
    "CountHidalgo": 137,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/02",
    "Count": 212,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 11,
    "CountHidalgo": 138,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/03",
    "Count": 212,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 139,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/04",
    "Count": 221,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 2,
    "CountHidalgo": 143,
    "CasesHidalgo": 12,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 7,
    "CountStarr": 4,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/05",
    "Count": 222,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 10,
    "CountHidalgo": 143,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 12,
    "CountStarr": 4,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/06",
    "Count": 210,
    "Cases": 15,
    "Deaths": 1,
    "Recoveries": 26,
    "CountHidalgo": 136,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 4,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/07",
    "Count": 216,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 7,
    "CountHidalgo": 143,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 2,
    "CountStarr": 8,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/08",
    "Count": 216,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 9,
    "CountHidalgo": 152,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 7
  },
  {
    "Date": "5/09",
    "Count": 225,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 9,
    "CountHidalgo": 161,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/10",
    "Count": 225,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 163,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/11",
    "Count": 221,
    "Cases": 15,
    "Deaths": 1,
    "Recoveries": 18,
    "CountHidalgo": 163,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 5,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/12",
    "Count": 222,
    "Cases": 17,
    "Deaths": 2,
    "Recoveries": 14,
    "CountHidalgo": 162,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 10,
    "CountStarr": 9,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/13",
    "Count": 214,
    "Cases": 25,
    "Deaths": 0,
    "Recoveries": 33,
    "CountHidalgo": 164,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 2,
    "CountStarr": 9,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/14",
    "Count": 204,
    "Cases": 13,
    "Deaths": 1,
    "Recoveries": 22,
    "CountHidalgo": 169,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 10,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/15",
    "Count": 207,
    "Cases": 19,
    "Deaths": 1,
    "Recoveries": 15,
    "CountHidalgo": 166,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 11,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/16",
    "Count": 194,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 31,
    "CountHidalgo": 166,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 11,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 3,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/17",
    "Count": 194,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 181,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 11,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/18",
    "Count": 206,
    "Cases": 16,
    "Deaths": 2,
    "Recoveries": 2,
    "CountHidalgo": 188,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 12,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/19",
    "Count": 209,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 10,
    "CountHidalgo": 194,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 12,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/20",
    "Count": 215,
    "Cases": 15,
    "Deaths": 2,
    "Recoveries": 7,
    "CountHidalgo": 197,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 12,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/21",
    "Count": 201,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 21,
    "CountHidalgo": 191,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 12,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/22",
    "Count": 199,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 17,
    "CountHidalgo": 194,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 13,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/23",
    "Count": 192,
    "Cases": 12,
    "Deaths": 1,
    "Recoveries": 18,
    "CountHidalgo": 194,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/24",
    "Count": 192,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 209,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/25",
    "Count": 192,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 216,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/26",
    "Count": 180,
    "Cases": 13,
    "Deaths": 0,
    "Recoveries": 25,
    "CountHidalgo": 198,
    "CasesHidalgo": 12,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 30,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/27",
    "Count": 176,
    "Cases": 20,
    "Deaths": 0,
    "Recoveries": 24,
    "CountHidalgo": 189,
    "CasesHidalgo": 21,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 30,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  }
];

export default DEFAULT_CORONA_DATA;
