const DEFAULT_CORONA_DATA = [
  {
    "Date": "3/18",
    "Count": 0,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/19",
    "Count": 1,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/20",
    "Count": 2,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 0,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/21",
    "Count": 6,
    "Cases": 4,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 1,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/22",
    "Count": 6,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 2,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/23",
    "Count": 6,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 2,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/24",
    "Count": 7,
    "Cases": 1,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 5,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/25",
    "Count": 10,
    "Cases": 3,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 8,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 0,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 0,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/26",
    "Count": 13,
    "Cases": 3,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 11,
    "CasesHidalgo": 3,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 3,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/27",
    "Count": 13,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 18,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/28",
    "Count": 20,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 27,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/29",
    "Count": 20,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 28,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/30",
    "Count": 26,
    "Cases": 6,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 38,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 2,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 1,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "3/31",
    "Count": 26,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 46,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/01",
    "Count": 37,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 62,
    "CasesHidalgo": 16,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/02",
    "Count": 55,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 79,
    "CasesHidalgo": 17,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/03",
    "Count": 52,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 10,
    "CountHidalgo": 86,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 5,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/04",
    "Count": 66,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 1,
    "CountHidalgo": 86,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 6,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 1,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/05",
    "Count": 76,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 99,
    "CasesHidalgo": 13,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/06",
    "Count": 89,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 0,
    "CountHidalgo": 113,
    "CasesHidalgo": 14,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/07",
    "Count": 89,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 7,
    "CountHidalgo": 127,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/08",
    "Count": 94,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 5,
    "CountHidalgo": 130,
    "CasesHidalgo": 11,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 8,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 4,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/09",
    "Count": 99,
    "Cases": 29,
    "Deaths": 2,
    "Recoveries": 22,
    "CountHidalgo": 136,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/10",
    "Count": 111,
    "Cases": 12,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 161,
    "CasesHidalgo": 35,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 10,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/11",
    "Count": 130,
    "Cases": 36,
    "Deaths": 0,
    "Recoveries": 17,
    "CountHidalgo": 168,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/12",
    "Count": 130,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 170,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/13",
    "Count": 143,
    "Cases": 21,
    "Deaths": 0,
    "Recoveries": 8,
    "CountHidalgo": 167,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/14",
    "Count": 163,
    "Cases": 23,
    "Deaths": 0,
    "Recoveries": 3,
    "CountHidalgo": 179,
    "CasesHidalgo": 19,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/15",
    "Count": 167,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 11,
    "CountHidalgo": 184,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 2,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 6,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/16",
    "Count": 170,
    "Cases": 16,
    "Deaths": 1,
    "Recoveries": 12,
    "CountHidalgo": 190,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 3,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 2,
    "CountWillacy": 6,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/17",
    "Count": 172,
    "Cases": 9,
    "Deaths": 1,
    "Recoveries": 6,
    "CountHidalgo": 194,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 3
  },
  {
    "Date": "4/18",
    "Count": 184,
    "Cases": 19,
    "Deaths": 1,
    "Recoveries": 6,
    "CountHidalgo": 207,
    "CasesHidalgo": 13,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/19",
    "Count": 184,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 213,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/20",
    "Count": 187,
    "Cases": 12,
    "Deaths": 1,
    "Recoveries": 8,
    "CountHidalgo": 206,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 14,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 1
  },
  {
    "Date": "4/21",
    "Count": 185,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 11,
    "CountHidalgo": 193,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 20,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/22",
    "Count": 173,
    "Cases": 12,
    "Deaths": 3,
    "Recoveries": 21,
    "CountHidalgo": 181,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 17,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/23",
    "Count": 177,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 5,
    "CountHidalgo": 167,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 23,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/24",
    "Count": 181,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 6,
    "CountHidalgo": 160,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 16,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 5,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/25",
    "Count": 193,
    "Cases": 12,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 164,
    "CasesHidalgo": 4,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 3,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/26",
    "Count": 193,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 169,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 7,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/27",
    "Count": 199,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 4,
    "CountHidalgo": 150,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 20,
    "CountStarr": 2,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/28",
    "Count": 200,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 8,
    "CountHidalgo": 147,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 7,
    "CountStarr": 2,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/29",
    "Count": 206,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 7,
    "CountHidalgo": 136,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 20,
    "CountStarr": 3,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "4/30",
    "Count": 207,
    "Cases": 11,
    "Deaths": 1,
    "Recoveries": 9,
    "CountHidalgo": 133,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 13,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/01",
    "Count": 212,
    "Cases": 9,
    "Deaths": 0,
    "Recoveries": 4,
    "CountHidalgo": 137,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/02",
    "Count": 212,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 11,
    "CountHidalgo": 138,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/03",
    "Count": 212,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 139,
    "CasesHidalgo": 1,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 3,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/04",
    "Count": 221,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 2,
    "CountHidalgo": 143,
    "CasesHidalgo": 12,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 7,
    "CountStarr": 4,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/05",
    "Count": 222,
    "Cases": 11,
    "Deaths": 0,
    "Recoveries": 10,
    "CountHidalgo": 143,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 12,
    "CountStarr": 4,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/06",
    "Count": 210,
    "Cases": 15,
    "Deaths": 1,
    "Recoveries": 26,
    "CountHidalgo": 136,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 4,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/07",
    "Count": 216,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 7,
    "CountHidalgo": 143,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 2,
    "CountStarr": 8,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 8,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/08",
    "Count": 216,
    "Cases": 11,
    "Deaths": 2,
    "Recoveries": 9,
    "CountHidalgo": 152,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 7
  },
  {
    "Date": "5/09",
    "Count": 225,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 9,
    "CountHidalgo": 161,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/10",
    "Count": 225,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 163,
    "CasesHidalgo": 2,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/11",
    "Count": 221,
    "Cases": 15,
    "Deaths": 1,
    "Recoveries": 18,
    "CountHidalgo": 163,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 5,
    "CountStarr": 8,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/12",
    "Count": 222,
    "Cases": 17,
    "Deaths": 2,
    "Recoveries": 14,
    "CountHidalgo": 162,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 10,
    "CountStarr": 9,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/13",
    "Count": 214,
    "Cases": 25,
    "Deaths": 0,
    "Recoveries": 33,
    "CountHidalgo": 164,
    "CasesHidalgo": 6,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 2,
    "CountStarr": 9,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/14",
    "Count": 204,
    "Cases": 13,
    "Deaths": 1,
    "Recoveries": 22,
    "CountHidalgo": 169,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 10,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/15",
    "Count": 207,
    "Cases": 19,
    "Deaths": 1,
    "Recoveries": 15,
    "CountHidalgo": 166,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 11,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/16",
    "Count": 194,
    "Cases": 18,
    "Deaths": 0,
    "Recoveries": 31,
    "CountHidalgo": 166,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 11,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 3,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/17",
    "Count": 194,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 181,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 11,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/18",
    "Count": 206,
    "Cases": 16,
    "Deaths": 2,
    "Recoveries": 2,
    "CountHidalgo": 188,
    "CasesHidalgo": 8,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 1,
    "CountStarr": 13,
    "CasesStarr": 5,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/19",
    "Count": 209,
    "Cases": 14,
    "Deaths": 1,
    "Recoveries": 10,
    "CountHidalgo": 194,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 13,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 2,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/20",
    "Count": 215,
    "Cases": 15,
    "Deaths": 2,
    "Recoveries": 7,
    "CountHidalgo": 197,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 14,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/21",
    "Count": 201,
    "Cases": 7,
    "Deaths": 0,
    "Recoveries": 21,
    "CountHidalgo": 191,
    "CasesHidalgo": 5,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 11,
    "CountStarr": 14,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/22",
    "Count": 199,
    "Cases": 15,
    "Deaths": 0,
    "Recoveries": 17,
    "CountHidalgo": 194,
    "CasesHidalgo": 10,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 7,
    "CountStarr": 15,
    "CasesStarr": 1,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/23",
    "Count": 192,
    "Cases": 12,
    "Deaths": 1,
    "Recoveries": 18,
    "CountHidalgo": 194,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 15,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/24",
    "Count": 192,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 209,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 15,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/25",
    "Count": 192,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 216,
    "CasesHidalgo": 7,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 15,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 3,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/26",
    "Count": 180,
    "Cases": 13,
    "Deaths": 0,
    "Recoveries": 25,
    "CountHidalgo": 198,
    "CasesHidalgo": 12,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 30,
    "CountStarr": 15,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/27",
    "Count": 176,
    "Cases": 20,
    "Deaths": 0,
    "Recoveries": 24,
    "CountHidalgo": 219,
    "CasesHidalgo": 21,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 18,
    "CasesStarr": 3,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/28",
    "Count": 170,
    "Cases": 12,
    "Deaths": 2,
    "Recoveries": 16,
    "CountHidalgo": 199,
    "CasesHidalgo": 11,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 31,
    "CountStarr": 18,
    "CasesStarr": 6,
    "DeathsStarr": 0,
    "RecoveriesStarr": 6,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/29",
    "Count": 166,
    "Cases": 11,
    "Deaths": 1,
    "Recoveries": 14,
    "CountHidalgo": 208,
    "CasesHidalgo": 12,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 3,
    "CountStarr": 18,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/30",
    "Count": 169,
    "Cases": 10,
    "Deaths": 0,
    "Recoveries": 7,
    "CountHidalgo": 208,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 18,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "5/31",
    "Count": 169,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 223,
    "CasesHidalgo": 15,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 18,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 4,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/01",
    "Count": 174,
    "Cases": 12,
    "Deaths": 0,
    "Recoveries": 7,
    "CountHidalgo": 222,
    "CasesHidalgo": 9,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 9,
    "CountStarr": 17,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 5,
    "CountWillacy": 7,
    "CasesWillacy": 3,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/02",
    "Count": 182,
    "Cases": 23,
    "Deaths": 0,
    "Recoveries": 15,
    "CountHidalgo": 232,
    "CasesHidalgo": 26,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 16,
    "CountStarr": 17,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 7,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/03",
    "Count": 182,
    "Cases": 21,
    "Deaths": 3,
    "Recoveries": 18,
    "CountHidalgo": 241,
    "CasesHidalgo": 24,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 15,
    "CountStarr": 17,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 2,
    "CountWillacy": 7,
    "CasesWillacy": 0,
    "DeathsWillacy": 1,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/04",
    "Count": 201,
    "Cases": 21,
    "Deaths": 0,
    "Recoveries": 2,
    "CountHidalgo": 265,
    "CasesHidalgo": 45,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 21,
    "CountStarr": 17,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 7,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/05",
    "Count": 209,
    "Cases": 22,
    "Deaths": 0,
    "Recoveries": 14,
    "CountHidalgo": 268,
    "CasesHidalgo": 22,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 18,
    "CountStarr": 17,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 12,
    "CasesWillacy": 6,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/06",
    "Count": 225,
    "Cases": 29,
    "Deaths": 0,
    "Recoveries": 13,
    "CountHidalgo": 268,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 27,
    "CasesStarr": 13,
    "DeathsStarr": 1,
    "RecoveriesStarr": 0,
    "CountWillacy": 16,
    "CasesWillacy": 4,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/07",
    "Count": 225,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 300,
    "CasesHidalgo": 32,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 32,
    "CasesStarr": 5,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 16,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/08",
    "Count": 235,
    "Cases": 27,
    "Deaths": 0,
    "Recoveries": 17,
    "CountHidalgo": 324,
    "CasesHidalgo": 26,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 2,
    "CountStarr": 36,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 25,
    "CasesWillacy": 9,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/09",
    "Count": 253,
    "Cases": 32,
    "Deaths": 1,
    "Recoveries": 13,
    "CountHidalgo": 343,
    "CasesHidalgo": 45,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 26,
    "CountStarr": 37,
    "CasesStarr": 8,
    "DeathsStarr": 0,
    "RecoveriesStarr": 7,
    "CountWillacy": 28,
    "CasesWillacy": 3,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/10",
    "Count": 262,
    "Cases": 39,
    "Deaths": 2,
    "Recoveries": 28,
    "CountHidalgo": 366,
    "CasesHidalgo": 38,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 15,
    "CountStarr": 37,
    "CasesStarr": 3,
    "DeathsStarr": 0,
    "RecoveriesStarr": 3,
    "CountWillacy": 29,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/11",
    "Count": 283,
    "Cases": 41,
    "Deaths": 2,
    "Recoveries": 18,
    "CountHidalgo": 406,
    "CasesHidalgo": 70,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 30,
    "CountStarr": 62,
    "CasesStarr": 25,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 34,
    "CasesWillacy": 5,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/12",
    "Count": 293,
    "Cases": 50,
    "Deaths": 0,
    "Recoveries": 40,
    "CountHidalgo": 441,
    "CasesHidalgo": 55,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 20,
    "CountStarr": 64,
    "CasesStarr": 2,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 40,
    "CasesWillacy": 6,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/13",
    "Count": 334,
    "Cases": 57,
    "Deaths": 0,
    "Recoveries": 16,
    "CountHidalgo": 441,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 83,
    "CasesStarr": 19,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 42,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/14",
    "Count": 334,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 524,
    "CasesHidalgo": 83,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 93,
    "CasesStarr": 12,
    "DeathsStarr": 0,
    "RecoveriesStarr": 2,
    "CountWillacy": 42,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/15",
    "Count": 353,
    "Cases": 40,
    "Deaths": 0,
    "Recoveries": 21,
    "CountHidalgo": 571,
    "CasesHidalgo": 62,
    "DeathsHidalgo": 3,
    "RecoveriesHidalgo": 12,
    "CountStarr": 119,
    "CasesStarr": 26,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 42,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/16",
    "Count": 384,
    "Cases": 58,
    "Deaths": 1,
    "Recoveries": 26,
    "CountHidalgo": 659,
    "CasesHidalgo": 143,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 53,
    "CountStarr": 132,
    "CasesStarr": 13,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 46,
    "CasesWillacy": 4,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/17",
    "Count": 429,
    "Cases": 65,
    "Deaths": 2,
    "Recoveries": 18,
    "CountHidalgo": 733,
    "CasesHidalgo": 92,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 16,
    "CountStarr": 132,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 52,
    "CasesWillacy": 6,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/18",
    "Count": 466,
    "Cases": 70,
    "Deaths": 1,
    "Recoveries": 32,
    "CountHidalgo": 796,
    "CasesHidalgo": 100,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 36,
    "CountStarr": 181,
    "CasesStarr": 50,
    "DeathsStarr": 1,
    "RecoveriesStarr": 0,
    "CountWillacy": 52,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/19",
    "Count": 527,
    "Cases": 83,
    "Deaths": 0,
    "Recoveries": 22,
    "CountHidalgo": 861,
    "CasesHidalgo": 109,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 43,
    "CountStarr": 181,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 19,
    "CountWillacy": 52,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/20",
    "Count": 554,
    "Cases": 92,
    "Deaths": 0,
    "Recoveries": 65,
    "CountHidalgo": 861,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 268,
    "CasesStarr": 106,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 52,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/21",
    "Count": 554,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 951,
    "CasesHidalgo": 133,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 42,
    "CountStarr": 271,
    "CasesStarr": 3,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 52,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/22",
    "Count": 596,
    "Cases": 101,
    "Deaths": 1,
    "Recoveries": 58,
    "CountHidalgo": 1120,
    "CasesHidalgo": 193,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 23,
    "CountStarr": 323,
    "CasesStarr": 53,
    "DeathsStarr": 1,
    "RecoveriesStarr": 0,
    "CountWillacy": 52,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/23",
    "Count": 646,
    "Cases": 111,
    "Deaths": 1,
    "Recoveries": 60,
    "CountHidalgo": 1344,
    "CasesHidalgo": 248,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 22,
    "CountStarr": 323,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 18,
    "CountWillacy": 73,
    "CasesWillacy": 21,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/24",
    "Count": 696,
    "Cases": 123,
    "Deaths": 2,
    "Recoveries": 71,
    "CountHidalgo": 1666,
    "CasesHidalgo": 373,
    "DeathsHidalgo": 4,
    "RecoveriesHidalgo": 47,
    "CountStarr": 368,
    "CasesStarr": 78,
    "DeathsStarr": 0,
    "RecoveriesStarr": 15,
    "CountWillacy": 105,
    "CasesWillacy": 32,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/25",
    "Count": 702,
    "Cases": 91,
    "Deaths": 0,
    "Recoveries": 85,
    "CountHidalgo": 1796,
    "CasesHidalgo": 210,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 80,
    "CountStarr": 374,
    "CasesStarr": 26,
    "DeathsStarr": 0,
    "RecoveriesStarr": 20,
    "CountWillacy": 105,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/26",
    "Count": 748,
    "Cases": 113,
    "Deaths": 2,
    "Recoveries": 65,
    "CountHidalgo": 1918,
    "CasesHidalgo": 179,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 55,
    "CountStarr": 414,
    "CasesStarr": 58,
    "DeathsStarr": 0,
    "RecoveriesStarr": 18,
    "CountWillacy": 116,
    "CasesWillacy": 11,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/27",
    "Count": 738,
    "Cases": 98,
    "Deaths": 1,
    "Recoveries": 107,
    "CountHidalgo": 1918,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 425,
    "CasesStarr": 11,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 128,
    "CasesWillacy": 12,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/28",
    "Count": 738,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 2190,
    "CasesHidalgo": 402,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 129,
    "CountStarr": 471,
    "CasesStarr": 46,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 138,
    "CasesWillacy": 10,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/29",
    "Count": 775,
    "Cases": 113,
    "Deaths": 0,
    "Recoveries": 76,
    "CountHidalgo": 2412,
    "CasesHidalgo": 248,
    "DeathsHidalgo": 3,
    "RecoveriesHidalgo": 23,
    "CountStarr": 489,
    "CasesStarr": 18,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 141,
    "CasesWillacy": 3,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "6/30",
    "Count": 805,
    "Cases": 103,
    "Deaths": 0,
    "Recoveries": 73,
    "CountHidalgo": 2786,
    "CasesHidalgo": 440,
    "DeathsHidalgo": 11,
    "RecoveriesHidalgo": 55,
    "CountStarr": 569,
    "CasesStarr": 102,
    "DeathsStarr": 0,
    "RecoveriesStarr": 22,
    "CountWillacy": 143,
    "CasesWillacy": 2,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/01",
    "Count": 817,
    "Cases": 111,
    "Deaths": 1,
    "Recoveries": 98,
    "CountHidalgo": 3026,
    "CasesHidalgo": 270,
    "DeathsHidalgo": 3,
    "RecoveriesHidalgo": 27,
    "CountStarr": 587,
    "CasesStarr": 24,
    "DeathsStarr": 0,
    "RecoveriesStarr": 6,
    "CountWillacy": 155,
    "CasesWillacy": 12,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/02",
    "Count": 844,
    "Cases": 101,
    "Deaths": 4,
    "Recoveries": 70,
    "CountHidalgo": 3204,
    "CasesHidalgo": 268,
    "DeathsHidalgo": 7,
    "RecoveriesHidalgo": 83,
    "CountStarr": 668,
    "CasesStarr": 81,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 155,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/03",
    "Count": 833,
    "Cases": 81,
    "Deaths": 3,
    "Recoveries": 89,
    "CountHidalgo": 3142,
    "CasesHidalgo": 278,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 339,
    "CountStarr": 703,
    "CasesStarr": 40,
    "DeathsStarr": 5,
    "RecoveriesStarr": 0,
    "CountWillacy": 194,
    "CasesWillacy": 39,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/04",
    "Count": 708,
    "Cases": 87,
    "Deaths": 4,
    "Recoveries": 208,
    "CountHidalgo": 3142,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 0,
    "CountStarr": 703,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 192,
    "CasesWillacy": 18,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 20
  },
  {
    "Date": "7/05",
    "Count": 708,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 3452,
    "CasesHidalgo": 547,
    "DeathsHidalgo": 1,
    "RecoveriesHidalgo": 235,
    "CountStarr": 703,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 200,
    "CasesWillacy": 8,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/06",
    "Count": 739,
    "Cases": 101,
    "Deaths": 1,
    "Recoveries": 69,
    "CountHidalgo": 2975,
    "CasesHidalgo": 102,
    "DeathsHidalgo": 16,
    "RecoveriesHidalgo": 563,
    "CountStarr": 707,
    "CasesStarr": 4,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 200,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/07",
    "Count": 747,
    "Cases": 117,
    "Deaths": 2,
    "Recoveries": 107,
    "CountHidalgo": 2955,
    "CasesHidalgo": 335,
    "DeathsHidalgo": 15,
    "RecoveriesHidalgo": 340,
    "CountStarr": 666,
    "CasesStarr": 69,
    "DeathsStarr": 0,
    "RecoveriesStarr": 110,
    "CountWillacy": 209,
    "CasesWillacy": 9,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/08",
    "Count": 764,
    "Cases": 123,
    "Deaths": 1,
    "Recoveries": 105,
    "CountHidalgo": 3160,
    "CasesHidalgo": 278,
    "DeathsHidalgo": 13,
    "RecoveriesHidalgo": 60,
    "CountStarr": 735,
    "CasesStarr": 69,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 210,
    "CasesWillacy": 1,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/09",
    "Count": 834,
    "Cases": 126,
    "Deaths": 0,
    "Recoveries": 56,
    "CountHidalgo": 4375,
    "CasesHidalgo": 1274,
    "DeathsHidalgo": 20,
    "RecoveriesHidalgo": 39,
    "CountStarr": 735,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 218,
    "CasesWillacy": 8,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/10",
    "Count": 1015,
    "Cases": 250,
    "Deaths": 6,
    "Recoveries": 63,
    "CountHidalgo": 4696,
    "CasesHidalgo": 393,
    "DeathsHidalgo": 19,
    "RecoveriesHidalgo": 53,
    "CountStarr": 762,
    "CasesStarr": 27,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 223,
    "CasesWillacy": 5,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/11",
    "Count": 1227,
    "Cases": 358,
    "Deaths": 2,
    "Recoveries": 144,
    "CountHidalgo": 4696,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 751,
    "CasesStarr": 25,
    "DeathsStarr": 0,
    "RecoveriesStarr": 36,
    "CountWillacy": 234,
    "CasesWillacy": 11,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/12",
    "Count": 1227,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 4874,
    "CasesHidalgo": 313,
    "DeathsHidalgo": 8,
    "RecoveriesHidalgo": 127,
    "CountStarr": 796,
    "CasesStarr": 45,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 292,
    "CasesWillacy": 58,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/13",
    "Count": 1506,
    "Cases": 321,
    "Deaths": 0,
    "Recoveries": 42,
    "CountHidalgo": 4666,
    "CasesHidalgo": 157,
    "DeathsHidalgo": 2,
    "RecoveriesHidalgo": 363,
    "CountStarr": 807,
    "CasesStarr": 11,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 313,
    "CasesWillacy": 21,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/14",
    "Count": 1884,
    "Cases": 415,
    "Deaths": 0,
    "Recoveries": 37,
    "CountHidalgo": 5031,
    "CasesHidalgo": 396,
    "DeathsHidalgo": 31,
    "RecoveriesHidalgo": 0,
    "CountStarr": 862,
    "CasesStarr": 55,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 323,
    "CasesWillacy": 10,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/15",
    "Count": 2156,
    "Cases": 315,
    "Deaths": 0,
    "Recoveries": 43,
    "CountHidalgo": 4871,
    "CasesHidalgo": 651,
    "DeathsHidalgo": 35,
    "RecoveriesHidalgo": 776,
    "CountStarr": 909,
    "CasesStarr": 47,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 377,
    "CasesWillacy": 54,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/16",
    "Count": 2428,
    "Cases": 335,
    "Deaths": 10,
    "Recoveries": 53,
    "CountHidalgo": 5900,
    "CasesHidalgo": 1248,
    "DeathsHidalgo": 22,
    "RecoveriesHidalgo": 197,
    "CountStarr": 1056,
    "CasesStarr": 147,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 407,
    "CasesWillacy": 30,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  },
  {
    "Date": "7/17",
    "Count": 2428,
    "Cases": 0,
    "Deaths": 0,
    "Recoveries": 0,
    "CountHidalgo": 5900,
    "CasesHidalgo": 0,
    "DeathsHidalgo": 0,
    "RecoveriesHidalgo": 0,
    "CountStarr": 1056,
    "CasesStarr": 0,
    "DeathsStarr": 0,
    "RecoveriesStarr": 0,
    "CountWillacy": 407,
    "CasesWillacy": 0,
    "DeathsWillacy": 0,
    "RecoveriesWillacy": 0
  }
];

export default DEFAULT_CORONA_DATA;
